#pragma config(Sensor, S1,     Bump,           sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S2,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S3,     Color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     Angle,          sensorEV3_Gyro)
#pragma config(Motor,  motorA,          engineA,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          engineB,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          SengineC,      tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	short currentColour;
	resetGyro(S4);
	while (true)
	{
		// Colours range from 0 to 7
		// None    = 0
		// Black   = 1
		// Blue    = 2
		// Green   = 3
		// Yellow  = 4
		// Red     = 5
		// White   = 6
		// Brown   = 7
		currentColour = SensorValue[Color];

		switch(currentColour)
		{
		case 0:  displayCenteredBigTextLine(4, "none"); break;
		case 1:  displayCenteredBigTextLine(4, "black"); break;
		case 2:	 displayCenteredBigTextLine(4, "blue"); break;
		case 3:	 displayCenteredBigTextLine(4, "green"); break;
		case 4:	 displayCenteredBigTextLine(4, "yellow"); break;
		case 5:	 displayCenteredBigTextLine(4, "red"); break;
		case 6:	 displayCenteredBigTextLine(4, "white"); break;
		case 7:	 displayCenteredBigTextLine(4, "brown"); break;
		default: displayCenteredBigTextLine(4, "unknown");
		}


		// Wait 20 ms to get 50 readings per second
		sleep(20);


		if ((currentColour == 3) && (SensorValue(S2)==1)){

			int startTime = time1[T1];
			while (time1[T1] - startTime < 5000) {
				setMotor(motorA,20);
				setMotor(motorB,20);

				if (SensorValue[S4]<-3){
					// Wenn der Sensorwert von Sensor 3 gleich 3 ist oder der Sensorwert von Sensor 4 kleiner als -3 ist
					setMotor(motorA,20);
					setMotor(motorB,-20);
				}

				else if(SensorValue[S4] > 3) {
					// Wenn der Sensorwert von Sensor 4 größer als 3 ist
					setMotor(motorA,-20);
					setMotor(motorB,20);
				}
			}
			//Fahrzeug dreht sich um 90 Grad
			repeatUntil(getGyroHeading(S4) == 80)
			{
				setMotor(motorA, 5);
				setMotor(motorB, -5);
			}
			stopMotor(motorA);
			stopMotor(motorB);

			//Drehung von Motor C um 90 Grad
			moveMotorTarget(motorD, 90, 10);
			sleep(1000);
			//Drehung von Motor C auf Ausgangsposition
			moveMotorTarget(motorD,90,-10);
			waitUntilMotorStop(motorD);

			// back to home
			// turn back
			repeatUntil(getGyroHeading(S4) == -5){
				setMotor(motorA, -5);
				setMotor(motorB, 5);
			}
			stopMotor(motorA);
			stopMotor(motorB);
			startTime = time1[T1];
			while	(time1[T1] - startTime < 5000) {
				setMotor(motorA,-20);
				setMotor(motorB,-20);
			}
			stopMotor(motorA);
			stopMotor(motorB);
}

if ((currentColour == 2) && (SensorValue(S2)==1)){

			int startTime = time1[T1];
			while (time1[T1] - startTime < 11000) {
				setMotor(motorA,20);
				setMotor(motorB,20);

				if (SensorValue[S4]<-3){
					// Wenn der Sensorwert von Sensor 3 gleich 3 ist oder der Sensorwert von Sensor 4 kleiner als -3 ist
					setMotor(motorA,20);
					setMotor(motorB,-20);
				}

				else if(SensorValue[S4] > 3) {
					// Wenn der Sensorwert von Sensor 4 größer als 3 ist
					setMotor(motorA,-20);
					setMotor(motorB,20);
				}
			}
			//Fahrzeug dreht sich um 90 Grad
			repeatUntil(getGyroHeading(S4) == 80)
			{
				setMotor(motorA, 5);
				setMotor(motorB, -5);
			}
			stopMotor(motorA);
			stopMotor(motorB);

			//Drehung von Motor C um 90 Grad
			moveMotorTarget(motorD, 90, 10);
			sleep(1000);
			//Drehung von Motor C auf Ausgangsposition
			moveMotorTarget(motorD,90,-10);
			waitUntilMotorStop(motorD);

			// back to home
			// turn back
			repeatUntil(getGyroHeading(S4) == -5){
				setMotor(motorA, -5);
				setMotor(motorB, 5);
			}
			stopMotor(motorA);
			stopMotor(motorB);
			startTime = time1[T1];
			while	(time1[T1] - startTime < 11000) {
				setMotor(motorA,-20);
				setMotor(motorB,-20);
			}
			stopMotor(motorA);
			stopMotor(motorB);
		}
if ((currentColour == 4) && (SensorValue(S2)==1)){

			int startTime = time1[T1];
			while (time1[T1] - startTime < 8000) {
				setMotor(motorA,20);
				setMotor(motorB,20);

				if (SensorValue[S4]<-3){
					// Wenn der Sensorwert von Sensor 3 gleich 3 ist oder der Sensorwert von Sensor 4 kleiner als -3 ist
					setMotor(motorA,20);
					setMotor(motorB,-20);
				}

				else if(SensorValue[S4] > 3) {
					// Wenn der Sensorwert von Sensor 4 größer als 3 ist
					setMotor(motorA,-20);
					setMotor(motorB,20);
				}
			}
			//Fahrzeug dreht sich um 90 Grad
			repeatUntil(getGyroHeading(S4) == 80)
			{
				setMotor(motorA, 5);
				setMotor(motorB, -5);
			}
			stopMotor(motorA);
			stopMotor(motorB);

			//Drehung von Motor C um 90 Grad
			moveMotorTarget(motorD, 90, 10);
			sleep(1000);
			//Drehung von Motor C auf Ausgangsposition
			moveMotorTarget(motorD,90,-10);
			waitUntilMotorStop(motorD);

			// back to home
			// turn back
			repeatUntil(getGyroHeading(S4) == -5){
				setMotor(motorA, -5);
				setMotor(motorB, 5);
			}
			stopMotor(motorA);
			stopMotor(motorB);
			startTime = time1[T1];
			while	(time1[T1] - startTime < 8000) {
				setMotor(motorA,-20);
				setMotor(motorB,-20);
			}
			stopMotor(motorA);
			stopMotor(motorB);
		}
if ((currentColour == 5) && (SensorValue(S2)==1)){

			int startTime = time1[T1];
			while (time1[T1] - startTime < 14000) {
				setMotor(motorA,20);
				setMotor(motorB,20);

				if (SensorValue[S4]<-3){
					// Wenn der Sensorwert von Sensor 3 gleich 3 ist oder der Sensorwert von Sensor 4 kleiner als -3 ist
					setMotor(motorA,20);
					setMotor(motorB,-20);
				}

				else if(SensorValue[S4] > 3) {
					// Wenn der Sensorwert von Sensor 4 größer als 3 ist
					setMotor(motorA,-20);
					setMotor(motorB,20);
				}
			}
			//Fahrzeug dreht sich um 90 Grad
			repeatUntil(getGyroHeading(S4) == 80)
			{
				setMotor(motorA, 5);
				setMotor(motorB, -5);
			}
			stopMotor(motorA);
			stopMotor(motorB);

			//Drehung von Motor C um 90 Grad
			moveMotorTarget(motorD, 90, 10);
			sleep(1000);
			//Drehung von Motor C auf Ausgangsposition
			moveMotorTarget(motorD,90,-10);
			waitUntilMotorStop(motorD);

			// back to home
			// turn back
			repeatUntil(getGyroHeading(S4) == -5){
				setMotor(motorA, -5);
				setMotor(motorB, 5);
			}
			stopMotor(motorA);
			stopMotor(motorB);
			startTime = time1[T1];
			while	(time1[T1] - startTime < 14000) {
				setMotor(motorA,-20);
				setMotor(motorB,-20);
			}
			stopMotor(motorA);
			stopMotor(motorB);
		}
	}

}
